# Schema for the configuration files of the mbw_shipping module.
mbw_payment.settings:
  type: config_object
  label: 'MBW Payment Settings'
  mapping:
    store_id:
      type: string
      label: 'Store ID'
    api_key:
      type: string
      label: 'API Key'
    checkout_id:
      type: string
      label: 'Checkout UID'
    environment:
      type: list_string
      label: 'Environment'
      settings:
        allowed_values:
          - value: qa
            label: QA
          - value: prod
            label: Production
      default_value: qa
    request_endpoint_qa:
      type: string
      label: 'Request Endpoint (QA)'
    request_endpoint_prod:
      type: string
      label: 'Request Endpoint (Production)'
