# Schema for the configuration files of the mbw_shipping module.
mbw_shiptrack.settings:
  type: config_object
  label: 'MBW ShipTrack Settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    endpoint:
      type: string
      label: 'Endpoint'
